version: '3.1'

services:
  shippy-cli-consignment:
    build:
      ./shippy-cli-consignment

  shippy-service-consignment:
    build:
      ./shippy-service-consignment
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "mongodb://admin:LTYlty0123@datastore:27017"

  shippy-service-vessel:
    build:
      ./shippy-service-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "mongodb://admin:LTYlty0123@datastore:27017"

  user-service:
    build: ./shippy-service-user
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432