version: '3.1'

services:
  shippy-cli-consignment:
    build:
      ./shippy-cli-consignment

  shippy-service-consignment:
    build:
      ./shippy-service-consignment
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "mongodb://admin:LTYlty0123@datastore:27017"

  shippy-service-vessel:
    build:
      ./shippy-service-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "mongodb://admin:LTYlty0123@datastore:27017"

  shippy-service-user:
    build: ./shippy-service-user
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "database"
      DB_USER: "postgres"
      DB_NAME: "shippy"
      DB_PASSWORD: "LTYlty0123"

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: LTYlty0123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /Users/linty/data/docker/postgres/data:/var/lib/postgresql/data/pgdata